### ISSUE TITLE
Loosen Django upper bound for Django 6.1 (cap causes a silent downgrade to the broken 4.0.1)

### ISSUE THREAD

**Issue by violuke** [panevo/django-celery-email-reboot#19]
Hi, following the same pattern as #6 for Django 6.0, could the Django upper bound be loosened for Django 6.1 (released 2026-08-05)?

The current pin in [`setup.py`](https://github.com/panevo/django-celery-email-reboot/blob/master/setup.py#L43) is:

```python
# Django for Python 3.12, 3.13 and 3.14
"Django>=4.2,<6.1; python_version >= '3.12'",
```

## Why this is worth prioritising over a normal version bump

The `<6.1` cap doesn't just prevent installation. Because 4.0.1 has no upper bound at all (`Django>=3.0`), resolvers **backtrack silently to 4.0.1 rather than failing**, and 4.0.1 is broken on Django 6.0+.

With `django~=6.1.0` in our `pyproject.toml`, uv resolved `django-celery-email-reboot` from 4.2.1 down to 4.0.1 (May 2024). Nothing in the resolution failed and nothing warned; it only showed up as a one-line change in the lock file.

4.0.1 predates the Django 6.0 email rewrite and reads `message.mixed_subtype` unguarded in `email_to_dict()`. `EmailMessage.mixed_subtype` was removed in Django 6.0 (present in 5.2, absent in 6.0 and 6.1), so:

```python
# Django 6.1 + django-celery-email-reboot 4.0.1
from django.core.mail import EmailMultiAlternatives
from djcelery_email.utils import email_to_dict

msg = EmailMultiAlternatives("Subject", "body", "a@example.com", ["b@example.com"])
msg.attach_alternative("<p>body</p>", "text/html")
email_to_dict(msg)
```

```
AttributeError: 'EmailMultiAlternatives' object has no attribute 'mixed_subtype'
```

`CeleryEmailBackend.send_messages()` calls `email_to_dict()` on every message, so for anyone using this backend in production the effect is that **all outbound email fails**. The guard added in 4.2.0 (`hasattr(message, 'mixed_subtype')`) is exactly what fixes this, and the cap is what prevents people from getting it.

## The 4.2.1 code appears to already work on 6.1

The cap looks precautionary rather than a real incompatibility. Running 4.2.1's `utils.py` against Django 6.1, a full `email_to_dict()` -> `dict_to_email()` round trip succeeded with alternatives, file attachments and a custom attribute via `CELERY_EMAIL_MESSAGE_EXTRA_ATTRIBUTES` all preserved, and the reconstructed message rendered via `.message()`.

So loosening the bound and adding a `dj61` env to `tox.ini` may be all that's needed.

## Related but separate

#18 covers the new `EMAIL_PROVIDERS` / `mail.providers[alias]` machinery in 6.1 and the wrapper-backend guidance. I don't think lifting the version cap depends on that work, and given the silent-downgrade behaviour above there's a good case for decoupling the two so people on 6.1 aren't left on a broken 4.0.1 while the larger design question is settled.

Happy to open a PR for the bound plus a tox env if that's useful. Thanks for maintaining this.
